### ISSUE TITLE
negative structured metadata bytes received error when no structured metadata sent on write path

### ISSUE THREAD

**Issue by matthewhudsonedb** [grafana/loki#17371]
**Describe the bug**

Our loki write logs are littered with this error now because we are not sending any structured metadata through:

```
level=error ts=2025-04-22T05:12:50.759646919Z caller=push.go:190 org_id=fake traceID=24274f310f6d627f msg="negative structured metadata bytes received" userID=fake retentionHours=8784 isAggregatedMetric=false policyName= size=0
level=error ts=2025-04-22T05:12:51.856799821Z caller=push.go:190 org_id=fake traceID=58c8970101c4f3b1 msg="negative structured metadata bytes received" userID=fake retentionHours=8784 isAggregatedMetric=false policyName= size=0
level=error ts=2025-04-22T05:12:53.132847816Z caller=push.go:190 org_id=fake traceID=5109f365773bb490 msg="negative structured metadata bytes received" userID=fake retentionHours=8784 isAggregatedMetric=false policyName= size=0
```

This appears to be added with this change https://github.com/grafana/loki/pull/17056/files.
The prometheus counter Add method supports 0 values, but not negative. We should update this expression to `>=` so we are not generating unneccessary errors for logs with no structure metadata.

**To Reproduce**
1. Run latest weekly version: grafana/loki:k251-87922da
2. Send logs with no structured metadata.

**Expected behavior**
 We should update this expression to `>=` so we are not generating unneccessary errors for requests with no structured metadata.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Logs:
```
level=error ts=2025-04-22T05:12:50.759646919Z caller=push.go:190 org_id=fake traceID=24274f310f6d627f msg="negative structured metadata bytes received" userID=fake retentionHours=8784 isAggregatedMetric=false policyName= size=0
level=error ts=2025-04-22T05:12:51.856799821Z caller=push.go:190 org_id=fake traceID=58c8970101c4f3b1 msg="negative structured metadata bytes received" userID=fake retentionHours=8784 isAggregatedMetric=false policyName= size=0
level=error ts=2025-04-22T05:12:53.132847816Z caller=push.go:190 org_id=fake traceID=5109f365773bb490 msg="negative structured metadata bytes received" userID=fake retentionHours=8784 isAggregatedMetric=false policyName= size=0
```

**Comment by yuusungwoo** [comment]
@matthewhudsonedb 
This is the same error as me!
Have you solved this error now?

**Comment by matthewhudsonedb** [comment]
> [@matthewhudsonedb](https://github.com/matthewhudsonedb) This is exactly the same error I'm having! Have you solved this error now?

@yuusungwoo  Yes, there is a bug in the logic that isn't checking for requests with zero sized structured metadata. I have a PR ready for review awaiting a review: https://github.com/grafana/loki/pull/17372/files

**Comment by matthewhudsonedb** [comment]
This bug is introduced with latest release of Loki which is version 3.5.0.

**Comment by luistilingue** [comment]
> This bug is introduced with latest release of Loki which is version 3.5.0.

Yes, I'm facing it. It'll be great if 3.5.1 be released soon with that fix!

**Comment by yuusungwoo** [comment]
> > [@matthewhudsonedb](https://github.com/matthewhudsonedb) This is exactly the same error I'm having! Have you solved this error now?
> 
> [@yuusungwoo](https://github.com/yuusungwoo) Yes, there is a bug in the logic that isn't checking for requests with zero sized structured metadata. I have a PR awaiting a review: [#17372](https://github.com/grafana/loki/pull/17372)

@matthewhudsonedb cool, thanks for your great job

**Comment by AntoineGS** [comment]
Same here, thank god I had setup drive usage alerts 😂

**Comment by DenisKurko** [comment]
I was expecting that this problem will be several years old. But its only a week...
I've definitely chosen the best time to learn it

**Comment by lovrozitnik** [comment]
Same error. Using Grafana Alloy to send the data - and even if I set tenant_id="default" in loki.write.endpoint in the config on Grafana Alloy server - same problem. 

Loki docker version:
loki, version 3.5.0 (branch: k248, revision: 4b16bc4f)
  build user:       root@buildkitsandbox
  build date:       2025-04-17T19:14:57Z
  go version:       go1.24.2
  platform:         linux/amd64
  tags:             netgo

**Comment by matthewhudsonedb** [comment]
I have asked if the PR can be backport released to 3.5.x: https://github.com/grafana/loki/pull/17372#issuecomment-2841343386

**Comment by evilGmonkey** [comment]
has this been fixed or is there a temporary workaround?

**Comment by jbcodemonkey** [comment]
> I'm running my grafana/loki setup in docker. Pinned the Loki image to 3.4 (`grafana/loki:3.4`) and everything is stable again. This should hold me until the `3.5.1` release.

Good advice: getting a log entry every second or so. Rolling back to 3.4 was an easy fix.

**Comment by mhoyer** [comment]
> has this been fixed or is there a temporary workaround?

@evilGmonkey, if I read the comments in #17372 correctly, this PR is the fix, but not yet released with a 3.5.1+. We also wait before going to 3.5.x until this fix is released. Maybe @trevorwhitney can tell something about the schedule for the fix?

**Comment by rsommer** [comment]
Just rolled out 3.5.1, everything back to normal. Thanks!

**Comment by nickhelmet** [comment]
Do you know when the chart will be updated to support version 3.5.1?

**Comment by ruifung** [comment]
> is there any timeline for helm release?

In the meantime you can just override the image version with loki.image.tag in your values file?

**Comment by Numblesix** [comment]
Im running `enterprise-logs:3.5.1` and the issue is still present:

```
enterprise-logs-write-5 loki level=error ts=2025-06-04T10:47:18.90917322Z caller=push.go:202 org_id=foo msg="negative structured metadata bytes received" userID=foo retentionHours=2160 isAggregatedMetric=false policyName= size=0

```

**Comment by muffl0n** [comment]
3.5.1 also fixed this for me. Thank you!

Unfortunately, the latest helm chart release still uses 3.5.0. Sure, one can override the tag. But it would be awesome, if the version with the fix would be used!

**Comment by instadeep-cb** [comment]
I can confirm that pinning the tag to 3.5.1  fixed the issue on my end as well! 
Thank you so much!!

**Comment by muffl0n** [comment]
See [#18005: Helm: Chart uses 3.5.0 instead of 3.5.1](https://github.com/grafana/loki/issues/18005)

**Comment by garry-t** [comment]
tag 3.5.1 - fixed problem
