### ISSUE TITLE
Crashlookbackoff with "recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference""

### ISSUE THREAD

**Issue by sudip-moengage** [grafana/loki#3248]
**Describe the bug**
Service runs for a day or two later it goes on to crashloopbackoff.
It fails with following logs:

```
2021-01-27 18:54:42.026761 I | proto: duplicate proto type registered: ingester.Series
level=info ts=2021-01-27T18:54:42.030318392Z caller=main.go:130 msg="Starting Loki" version="(version=k41-fd619b6, branch=k41, revision=fd619b69)"
level=info ts=2021-01-27T18:54:42.030614885Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-01-27T18:54:42.03103619Z caller=table_manager.go:241 msg="loading table index_18652"
level=error ts=2021-01-27T18:54:42.031471165Z caller=log.go:150 msg="error running loki" err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:308\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:209\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:209\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**To Reproduce**
Don't know, I see different errors every week. Each time I clean up the disk and use a fresh installation, loki runs fine for a day or two.
Config is same as shared here: https://github.com/grafana/loki/issues/3219

**Expected behavior**
It should come up as usual. If I clean up the disk it comes up fine.

**Environment:**
Infrastructure: kubernetes
Deployment tool: helm
Am I doing wrong configuration?

**Comment by tricky42** [comment]
I experience the same problem right now on a system which was running for a few weeks now.

**Comment by woeye** [comment]
Same issue here. We are using Loki on Azure AKS. The storageClass is azurefile.

**Comment by cyriltovena** [comment]
Can you share the index file causing the error  please ?

**Comment by simonxxz** [comment]
Same issue here. Running loki on ceph for 30+ days and crashed. Redeployed without error. Don't know what caused this error.

**Comment by voigtste** [comment]
Same over here...

**Comment by owen-d** [comment]
This should be fixed in the upcoming 2.3 release. Please let us know it if persists.

**Comment by axelmarciano** [comment]
Same here !

**Comment by dvdlevanon** [comment]
Experienced the same issue when running out of disk space.

Tried to run with `-log.level=debug` in order to get the name of the exact corrupt file, unfortunately it add no extra logs.
`level=info ts=2021-08-01T08:38:39.196432153Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.1, branch=HEAD, revision=babea82ef)"
level=info ts=2021-08-01T08:38:39.196796111Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-08-01T08:38:39.196905603Z caller=modules.go:477 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-08-01T08:38:39.197473839Z caller=table_manager.go:241 msg="loading table index_18838"
level=error ts=2021-08-01T08:38:39.198331235Z caller=log.go:106 msg="error running loki" err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:319\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"`


@owen-d Could you please provide with more details, such as when 2.3 should be out, or what is the PR/Commit that fixes it?

**Comment by dpiessens** [comment]
Ran into the same issue running out of disk space. I resized the volume and removed and re-deployed the Helm install and it's still crashing. I attached a busybox container to the volume and validated it had additional disk space. Mine fails with the following log lines, is there a file I can remove to restart the process? Or should I attach an additional volume to have tiered storage?

```
level=info ts=2021-08-05T18:44:20.92045892Z caller=table_manager.go:241 msg="loading table index_18831"
level=error ts=2021-08-05T18:44:20.921204424Z caller=log.go:106 msg="error running loki" err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:319\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**Comment by sudip-moengage** [comment]
@dpiessens This is not related to disk size IMO

**Comment by singh-navpreet** [comment]
@owen-d  : i was getting same error. Then tried upgrade to 2.3.0 , but now getting different error:

`level=info ts=2021-09-29T15:11:14.943526359Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"
level=info ts=2021-09-29T15:11:14.944089869Z caller=server.go:239 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-09-29T15:11:14.94420667Z caller=modules.go:504 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-09-29T15:11:14.944711379Z caller=table_manager.go:241 msg="loading table index_18892"
unexpected fault address 0x7f7434ca0008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f7434ca0008 pc=0xe6d3c5]

goroutine 1 [running]:
runtime.throw(0x2532d52, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000735390 sp=0xc000735360 pc=0x4385b2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:731 +0x2c8 fp=0xc0007353c8 sp=0xc000735390 pc=0x44ff48
go.etcd.io/bbolt.(*Cursor).search(0xc000735558, 0x39252b8, 0x5, 0x5, 0x3)
	/src/loki/vendor/go.etcd.io/bbolt/cursor.go:249 +0x65 fp=0xc000735460 sp=0xc0007353c8 pc=0xe6d3c5
go.etcd.io/bbolt.(*Cursor).seek(0xc000735558, 0x39252b8, 0x5, 0x5, 0x0, 0x0, 0x0, 0x125490, 0x3fe0000000000000, 0xc000735588, ...)
	/src/loki/vendor/go.etcd.io/bbolt/cursor.go:159 +0x7d fp=0xc0007354d0 sp=0xc000735460 pc=0xe6cc5d
go.etcd.io/bbolt.(*Bucket).Bucket(0xc000498718, 0x39252b8, 0x5, 0x5, 0x0)
	/src/loki/vendor/go.etcd.io/bbolt/bucket.go:105 +0xda fp=0xc000735588 sp=0xc0007354d0 pc=0xe68b1a
go.etcd.io/bbolt.(*Tx).Bucket(...)
	/src/loki/vendor/go.etcd.io/bbolt/tx.go:101
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.loadBoltDBsFromDir.func1(0xc000498700, 0x1c50100, 0xc000498700)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:499 +0x5e fp=0xc0007355c8 sp=0xc000735588 pc=0x1c681de
go.etcd.io/bbolt.(*DB).View(0xc0001c1600, 0xc000735718, 0x0, 0x0)
	/src/loki/vendor/go.etcd.io/bbolt/db.go:725 +0x93 fp=0xc000735630 sp=0xc0007355c8 pc=0xe707b3
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.loadBoltDBsFromDir(0xc00064ccf0, 0x2c, 0xc000647bc0, 0xc0007357e8, 0x62c11f, 0xc00064ccf0)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:498 +0x7a5 fp=0xc000735788 sp=0xc000735630 pc=0x1c64725
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.LoadTable(0xc00064ccf0, 0x2c, 0xc0005d1840, 0x1a, 0x7f7434cae400, 0xc000637a60, 0x7f7434cae3d8, 0xc000654cd0, 0xc000647bc0, 0x0, ...)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:86 +0x46 fp=0xc0007357f8 sp=0xc000735788 pc=0x1c5fca6
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.(*TableManager).loadTables(0xc00047e000, 0xc000096910, 0xc000647bc0, 0xc00069e7c0)
	/src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:242 +0x4e7 fp=0xc000735a08 sp=0xc0007357f8 pc=0x1c66d47
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.NewTableManager(0xc0005d1840, 0x1a, 0xc0005d10a0, 0x20, 0xdf8475800, 0xa7a3582000, 0x7f7434cae3d8, 0xc000654cd0, 0x7f7434cae400, 0xc000637a60, ...)
	/src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:57 +0x1a5 fp=0xc000735b00 sp=0xc000735a08 pc=0x1c64fa5
github.com/grafana/loki/pkg/storage/stores/shipper.(*Shipper).init(0xc0002dcc60, 0x29c3858, 0xc000637a00, 0x29ad490, 0xc000096910, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/shipper_index_client.go:141 +0x48e fp=0xc000735c20 sp=0xc000735b00 pc=0x1c6b6ee
github.com/grafana/loki/pkg/storage/stores/shipper.NewShipper(0xc0005d10a0, 0x20, 0xc0006f1c30, 0xa, 0x2534911, 0x6, 0xc0005d1100, 0x1f, 0x4e94914f0000, 0x45d964b800, ...)
	/src/loki/pkg/storage/stores/shipper/shipper_index_client.go:103 +0x155 fp=0xc000735e28 sp=0xc000735c20 pc=0x1c6aff5
github.com/grafana/loki/pkg/storage.RegisterCustomIndexClients.func1(0x2182640, 0xc000244c60, 0xc0006f1b80, 0xe)
	/src/loki/pkg/storage/store.go:432 +0x1b4 fp=0xc000736f60 sp=0xc000735e28 pc=0x1c7caf4
github.com/cortexproject/cortex/pkg/chunk/storage.NewIndexClient(0xc0006f1b80, 0xe, 0x2534569, 0x6, 0x0, 0x4000000000000000, 0x4024000000000000, 0x0, 0x0, 0x186a0, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:230 +0xc0a fp=0xc000737290 sp=0xc000736f60 pc=0x1ab99ca
github.com/cortexproject/cortex/pkg/chunk/storage.NewStore(0x2534569, 0x6, 0x0, 0x4000000000000000, 0x4024000000000000, 0x0, 0x0, 0x186a0, 0x3ff4cccccccccccd, 0x3ff0000000000000, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:196 +0x76b fp=0xc000737e70 sp=0xc000737290 pc=0x1ab840b
github.com/grafana/loki/pkg/loki.(*Loki).initStore(0xc000894000, 0xc00069e740, 0xc0006a2870, 0xc0006a2840, 0xc000358a80)
	/src/loki/pkg/loki/modules.go:322 +0x350 fp=0xc0007430f0 sp=0xc000737e70 pc=0x1f273b0
github.com/grafana/loki/pkg/loki.(*Loki).initStore-fm(0x217e380, 0xc000652e10, 0x2533450, 0x5)
	/src/loki/pkg/loki/modules.go:286 +0x33 fp=0xc000743128 sp=0xc0007430f0 pc=0x1f2f6f3
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule(0xc000125300, 0x2530a0d, 0x3, 0xc000743280, 0xc000653380, 0x0, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103 +0x2ba fp=0xc000743230 sp=0xc000743128 pc=0x1ca70da
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc000125300, 0xc000431dd0, 0x1, 0x1, 0x299ee80, 0xc000465b00, 0x29d1a28)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75 +0x105 fp=0xc000743358 sp=0xc000743230 pc=0x1ca6d85
github.com/grafana/loki/pkg/loki.(*Loki).Run(0xc000894000, 0xc0005ddd00, 0x4)
	/src/loki/pkg/loki/loki.go:241 +0x65 fp=0xc0007434b8 sp=0xc000743358 pc=0x1f21ea5
main.main()
	/src/loki/cmd/loki/main.go:131 +0x57c fp=0xc000747f88 sp=0xc0007434b8 pc=0x1f3967c
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000747fe0 sp=0xc000747f88 pc=0x43adf6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000747fe8 sp=0xc000747fe0 pc=0x472621

goroutine 233 [chan receive]:
github.com/cortexproject/cortex/pkg/alertmanager.init.0.func1()
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:127 +0x55
created by github.com/cortexproject/cortex/pkg/alertmanager.init.0
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:123 +0x35

goroutine 155 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00013f580)
	/src/loki/vendor/go.opencensus.io/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
	/src/loki/vendor/go.opencensus.io/stats/view/worker.go:34 +0x68

goroutine 287 [select]:
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker(0xc0005deb60, 0xc000144820)
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:153 +0xa5
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController(0xc0005deb60)
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:148 +0x73
created by github.com/uber/jaeger-client-go.NewRemotelyControlledSampler
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:87 +0x125

goroutine 289 [select]:
github.com/uber/jaeger-client-go/utils.(*reconnectingUDPConn).reconnectLoop(0xc00032a9a0, 0x6fc23ac00)
	/src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:70 +0xc8
created by github.com/uber/jaeger-client-go/utils.newReconnectingUDPConn
	/src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:60 +0x10c

goroutine 290 [select]:
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc00008de60)
	/src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:296 +0xfe
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:237 +0x1a5

goroutine 296 [chan receive]:
github.com/cortexproject/cortex/pkg/ring/kv/consul.(*mockKV).loop(0xc000637620)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:54 +0x66
created by github.com/cortexproject/cortex/pkg/ring/kv/consul.NewInMemoryClientWithConfig
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:37 +0xd5

goroutine 309 [select]:
github.com/cortexproject/cortex/pkg/util/services.NewTimerService.func1(0x29bda20, 0xc00069e680, 0x0, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/services.go:31 +0x105
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc0000b95e0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190 +0x402
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:119 +0xb3

goroutine 315 [select]:
github.com/cortexproject/cortex/pkg/chunk/local.(*BoltIndexClient).loop(0xc000654cd0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:81 +0x111
created by github.com/cortexproject/cortex/pkg/chunk/local.NewBoltDBIndexClient
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:70 +0x10c`

**Comment by singh-navpreet** [comment]
Hi @owen-d  , i was getting same error after i resized the volume attached to pod in aks cluster.
Then upgraded to 2.3.0 but now started getting different error.

> `level=info ts=2021-09-29T15:11:14.943526359Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"
level=info ts=2021-09-29T15:11:14.944089869Z caller=server.go:239 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-09-29T15:11:14.94420667Z caller=modules.go:504 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-09-29T15:11:14.944711379Z caller=table_manager.go:241 msg="loading table index_18892"
unexpected fault address 0x7f7434ca0008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f7434ca0008 pc=0xe6d3c5]
goroutine 1 [running]:
runtime.throw(0x2532d52, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000735390 sp=0xc000735360 pc=0x4385b2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:731 +0x2c8 fp=0xc0007353c8 sp=0xc000735390 pc=0x44ff48
go.etcd.io/bbolt.(*Cursor).search(0xc000735558, 0x39252b8, 0x5, 0x5, 0x3)
	/src/loki/vendor/go.etcd.io/bbolt/cursor.go:249 +0x65 fp=0xc000735460 sp=0xc0007353c8 pc=0xe6d3c5
go.etcd.io/bbolt.(*Cursor).seek(0xc000735558, 0x39252b8, 0x5, 0x5, 0x0, 0x0, 0x0, 0x125490, 0x3fe0000000000000, 0xc000735588, ...)
	/src/loki/vendor/go.etcd.io/bbolt/cursor.go:159 +0x7d fp=0xc0007354d0 sp=0xc000735460 pc=0xe6cc5d
go.etcd.io/bbolt.(*Bucket).Bucket(0xc000498718, 0x39252b8, 0x5, 0x5, 0x0)
	/src/loki/vendor/go.etcd.io/bbolt/bucket.go:105 +0xda fp=0xc000735588 sp=0xc0007354d0 pc=0xe68b1a
go.etcd.io/bbolt.(*Tx).Bucket(...)
	/src/loki/vendor/go.etcd.io/bbolt/tx.go:101
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.loadBoltDBsFromDir.func1(0xc000498700, 0x1c50100, 0xc000498700)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:499 +0x5e fp=0xc0007355c8 sp=0xc000735588 pc=0x1c681de
go.etcd.io/bbolt.(*DB).View(0xc0001c1600, 0xc000735718, 0x0, 0x0)
	/src/loki/vendor/go.etcd.io/bbolt/db.go:725 +0x93 fp=0xc000735630 sp=0xc0007355c8 pc=0xe707b3
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.loadBoltDBsFromDir(0xc00064ccf0, 0x2c, 0xc000647bc0, 0xc0007357e8, 0x62c11f, 0xc00064ccf0)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:498 +0x7a5 fp=0xc000735788 sp=0xc000735630 pc=0x1c64725
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.LoadTable(0xc00064ccf0, 0x2c, 0xc0005d1840, 0x1a, 0x7f7434cae400, 0xc000637a60, 0x7f7434cae3d8, 0xc000654cd0, 0xc000647bc0, 0x0, ...)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:86 +0x46 fp=0xc0007357f8 sp=0xc000735788 pc=0x1c5fca6
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.(*TableManager).loadTables(0xc00047e000, 0xc000096910, 0xc000647bc0, 0xc00069e7c0)
	/src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:242 +0x4e7 fp=0xc000735a08 sp=0xc0007357f8 pc=0x1c66d47
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.NewTableManager(0xc0005d1840, 0x1a, 0xc0005d10a0, 0x20, 0xdf8475800, 0xa7a3582000, 0x7f7434cae3d8, 0xc000654cd0, 0x7f7434cae400, 0xc000637a60, ...)
	/src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:57 +0x1a5 fp=0xc000735b00 sp=0xc000735a08 pc=0x1c64fa5
github.com/grafana/loki/pkg/storage/stores/shipper.(*Shipper).init(0xc0002dcc60, 0x29c3858, 0xc000637a00, 0x29ad490, 0xc000096910, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/shipper_index_client.go:141 +0x48e fp=0xc000735c20 sp=0xc000735b00 pc=0x1c6b6ee
github.com/grafana/loki/pkg/storage/stores/shipper.NewShipper(0xc0005d10a0, 0x20, 0xc0006f1c30, 0xa, 0x2534911, 0x6, 0xc0005d1100, 0x1f, 0x4e94914f0000, 0x45d964b800, ...)
	/src/loki/pkg/storage/stores/shipper/shipper_index_client.go:103 +0x155 fp=0xc000735e28 sp=0xc000735c20 pc=0x1c6aff5
github.com/grafana/loki/pkg/storage.RegisterCustomIndexClients.func1(0x2182640, 0xc000244c60, 0xc0006f1b80, 0xe)
	/src/loki/pkg/storage/store.go:432 +0x1b4 fp=0xc000736f60 sp=0xc000735e28 pc=0x1c7caf4
github.com/cortexproject/cortex/pkg/chunk/storage.NewIndexClient(0xc0006f1b80, 0xe, 0x2534569, 0x6, 0x0, 0x4000000000000000, 0x4024000000000000, 0x0, 0x0, 0x186a0, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:230 +0xc0a fp=0xc000737290 sp=0xc000736f60 pc=0x1ab99ca
github.com/cortexproject/cortex/pkg/chunk/storage.NewStore(0x2534569, 0x6, 0x0, 0x4000000000000000, 0x4024000000000000, 0x0, 0x0, 0x186a0, 0x3ff4cccccccccccd, 0x3ff0000000000000, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:196 +0x76b fp=0xc000737e70 sp=0xc000737290 pc=0x1ab840b
github.com/grafana/loki/pkg/loki.(*Loki).initStore(0xc000894000, 0xc00069e740, 0xc0006a2870, 0xc0006a2840, 0xc000358a80)
	/src/loki/pkg/loki/modules.go:322 +0x350 fp=0xc0007430f0 sp=0xc000737e70 pc=0x1f273b0
github.com/grafana/loki/pkg/loki.(*Loki).initStore-fm(0x217e380, 0xc000652e10, 0x2533450, 0x5)
	/src/loki/pkg/loki/modules.go:286 +0x33 fp=0xc000743128 sp=0xc0007430f0 pc=0x1f2f6f3
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule(0xc000125300, 0x2530a0d, 0x3, 0xc000743280, 0xc000653380, 0x0, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103 +0x2ba fp=0xc000743230 sp=0xc000743128 pc=0x1ca70da
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc000125300, 0xc000431dd0, 0x1, 0x1, 0x299ee80, 0xc000465b00, 0x29d1a28)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75 +0x105 fp=0xc000743358 sp=0xc000743230 pc=0x1ca6d85
github.com/grafana/loki/pkg/loki.(*Loki).Run(0xc000894000, 0xc0005ddd00, 0x4)
	/src/loki/pkg/loki/loki.go:241 +0x65 fp=0xc0007434b8 sp=0xc000743358 pc=0x1f21ea5
main.main()
	/src/loki/cmd/loki/main.go:131 +0x57c fp=0xc000747f88 sp=0xc0007434b8 pc=0x1f3967c
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000747fe0 sp=0xc000747f88 pc=0x43adf6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000747fe8 sp=0xc000747fe0 pc=0x472621
goroutine 233 [chan receive]:
github.com/cortexproject/cortex/pkg/alertmanager.init.0.func1()
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:127 +0x55
created by github.com/cortexproject/cortex/pkg/alertmanager.init.0
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:123 +0x35
goroutine 155 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00013f580)
	/src/loki/vendor/go.opencensus.io/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
	/src/loki/vendor/go.opencensus.io/stats/view/worker.go:34 +0x68
goroutine 287 [select]:
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker(0xc0005deb60, 0xc000144820)
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:153 +0xa5
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController(0xc0005deb60)
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:148 +0x73
created by github.com/uber/jaeger-client-go.NewRemotelyControlledSampler
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:87 +0x125
goroutine 289 [select]:
github.com/uber/jaeger-client-go/utils.(*reconnectingUDPConn).reconnectLoop(0xc00032a9a0, 0x6fc23ac00)
	/src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:70 +0xc8
created by github.com/uber/jaeger-client-go/utils.newReconnectingUDPConn
	/src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:60 +0x10c
goroutine 290 [select]:
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc00008de60)
	/src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:296 +0xfe
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:237 +0x1a5
goroutine 296 [chan receive]:
github.com/cortexproject/cortex/pkg/ring/kv/consul.(*mockKV).loop(0xc000637620)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:54 +0x66
created by github.com/cortexproject/cortex/pkg/ring/kv/consul.NewInMemoryClientWithConfig
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:37 +0xd5
goroutine 309 [select]:
github.com/cortexproject/cortex/pkg/util/services.NewTimerService.func1(0x29bda20, 0xc00069e680, 0x0, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/services.go:31 +0x105
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc0000b95e0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190 +0x402
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:119 +0xb3
goroutine 315 [select]:
github.com/cortexproject/cortex/pkg/chunk/local.(*BoltIndexClient).loop(0xc000654cd0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:81 +0x111
created by github.com/cortexproject/cortex/pkg/chunk/local.NewBoltDBIndexClient
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:70 +0x10c`

**Comment by singh-navpreet** [comment]
Hi @owen-d , was getting same errors when i resized volume and restarted pod in AKS(loki version 2.2.0).
Then upgraded to 2.3.0 but now new errors appeared
[loki_error.log](https://github.com/grafana/loki/files/7253124/loki_error.log)
.

**Comment by saigha01** [comment]
any update here? have the same issue with the same setup worked for some time being and crashing now.
raised an incident [https://github.com/grafana/helm-charts/issues/1730](https://github.com/grafana/helm-charts/issues/1730) for the same. anyone able to get over this issue?

**Comment by jocelynthode** [comment]
I'm getting the same issue since a few days using: `grafana/loki:2.6.1`

**Comment by claratang98** [comment]
I am getting the same issue using grafana/loki-stack:2.8.2

here is the log error:

![image](https://user-images.githubusercontent.com/90296566/189277612-9b865962-985a-4960-b11f-e6e8a5db5ba6.png)

**Comment by vasyakrg** [comment]
I am getting the same issue

```
level=error ts=2022-09-15T03:54:52.007356924Z caller=index_set.go:265 table-name=index_19249 msg="sync failed, retrying it" err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference"
level=error ts=2022-09-15T03:54:52.007405845Z caller=index_set.go:104 table-name=index_19249 msg="failed to initialize table index_19249, cleaning it up" err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference"
recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference
error creating index client
```

**Comment by xzycn** [comment]
Hi, any progress on this?
The same error here with chart loki-simple-scalable-1.8.11 :(

**Comment by davidmateos** [comment]
Same issue here on Loki 2.4.2. Any workaround?

**Comment by S0b1t** [comment]
### Loki's pod falls off after a while
```
$ kubectl version -o yaml

clientVersion:
  buildDate: "2022-05-03T13:46:05Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4

serverVersion:
  buildDate: "2022-08-17T18:47:37Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: linux/amd64

```

```
$ helm version

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```


I added a Helm chart from the documentation [https://grafana.com/docs/loki/latest/installation/helm/install-scalable/](url) and [https://github.com/grafana/helm-charts](url)
```
$ helm repo add grafana https://grafana.github.io/helm-charts
$ helm repo update
```
**changed values**
```
loki:
  persistence:
    enabled: true
    storageClassName: nfs-client
    size: 30Gi
```
```
promtail:
  tolerations:
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    operator: Exists
```

**installation**
```
$ helm install loki-stack grafana/loki-stack -n monitoring -f loki-values.yaml
```

**status**
```
$ helm ls 

NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
loki-stack              monitoring      2               2023-01-10 10:59:07.569498213 +0500 +05 deployed        loki-stack-2.8.9                v2.6.1
```
pod is working
```
$ k get pod

NAME                                                     READY   STATUS    RESTARTS        AGE
loki-stack-0                                             1/1     Running   0               59m
loki-stack-promtail-68jnv                                1/1     Running   0               55m
loki-stack-promtail-97c72                                1/1     Running   0               55m
loki-stack-promtail-kp9g8                                1/1     Running   0               67m
loki-stack-promtail-krzv6                                1/1     Running   0               67m
loki-stack-promtail-xzrfg                                1/1     Running   0               67m
```

```
$ k get pvc

NAME                                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
storage-loki-stack-0                                                                                     Bound    pvc-a9daec92-b541-47a9-b59f-72996377ab02   30Gi       RWO            nfs-client     59m
```
```
$ k exec -it loki-stack-0 -- sh
$ df -h

Filesystem                Size      Used Available Use% Mounted on
overlay                  97.3G     17.1G     76.1G  18% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     5.8G         0      5.8G   0% /sys/fs/cgroup
/dev/mapper/ubuntu--vg-ubuntu--lv
                         97.3G     17.1G     76.1G  18% /tmp
172.30.44.157:/mnt/nfs_k8s_dynamic/monitoring-storage-loki-stack-0-pvc-a9daec92-b541-47a9-b59f-72996377ab02
                        195.8G      5.1G    182.6G   3% /data
tmpfs                    11.6G      4.0K     11.6G   0% /etc/loki
/dev/mapper/ubuntu--vg-ubuntu--lv
                         97.3G     17.1G     76.1G  18% /dev/termination-log
/dev/mapper/ubuntu--vg-ubuntu--lv
                         97.3G     17.1G     76.1G  18% /etc/resolv.conf
/dev/mapper/ubuntu--vg-ubuntu--lv
                         97.3G     17.1G     76.1G  18% /etc/hostname
/dev/mapper/ubuntu--vg-ubuntu--lv
                         97.3G     17.1G     76.1G  18% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    11.6G     12.0K     11.6G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     5.8G         0      5.8G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     5.8G         0      5.8G   0% /proc/scsi
tmpfs                     5.8G         0      5.8G   0% /sys/firmware
```

**after a while**
```
$ k describe pod loki-stack-0

Name:         loki-stack-0
Namespace:    monitoring
Priority:     0
Node:         ds-worker1/172.30.44.165
Start Time:   Tue, 10 Jan 2023 14:51:12 +0500
Labels:       app=loki
              controller-revision-hash=loki-stack-65cb46884c
              name=loki-stack
              release=loki-stack
              statefulset.kubernetes.io/pod-name=loki-stack-0
Annotations:  checksum/config: b7426dc30bbac01e54c43af7d1e183312a6d75e0203d448892a9ff0a3cd46f6e
              kubectl.kubernetes.io/restartedAt: 2023-01-10T14:51:09+05:00
              prometheus.io/port: http-metrics
              prometheus.io/scrape: true
Status:       Running
IP:           10.42.3.237
IPs:
  IP:           10.42.3.237
Controlled By:  StatefulSet/loki-stack
Containers:
  loki:
    Container ID:  docker://c24efa4c9b21ba76cb26151da17dd7a7d48ee3e508452b97b5f2847b5c4e0dd7
    Image:         grafana/loki:2.6.1
    Image ID:      docker-pullable://grafana/loki@sha256:1ee60f980950b00e505bd564b40f720132a0653b110e993043bb5940673d060a
    Ports:         3100/TCP, 9095/TCP, 7946/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      -config.file=/etc/loki/loki.yaml
    State:          Running
      Started:      Tue, 10 Jan 2023 16:12:23 +0500
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Jan 2023 16:11:23 +0500
      Finished:     Tue, 10 Jan 2023 16:12:22 +0500
    Ready:          True
    Restart Count:  2
    Liveness:       http-get http://:http-metrics/ready delay=45s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http-metrics/ready delay=45s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from storage (rw)
      /etc/loki from config (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2xnh9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  storage-loki-stack-0
    ReadOnly:   false
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  loki-stack
    Optional:    false
  kube-api-access-2xnh9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From     Message
  ----     ------     ----                ----     -------
  Warning  Unhealthy  43m                 kubelet  Readiness probe failed: Get "http://10.42.3.237:3100/ready": dial tcp 10.42.3.237:3100: connect: connection refused
  Warning  Unhealthy  43m                 kubelet  Liveness probe failed: Get "http://10.42.3.237:3100/ready": dial tcp 10.42.3.237:3100: connect: connection refused
  Normal   Killing    42m                 kubelet  Container loki failed liveness probe, will be restarted
  Normal   Started    42m (x3 over 123m)  kubelet  Started container loki
  Normal   Pulled     42m (x3 over 123m)  kubelet  Container image "grafana/loki:2.6.1" already present on machine
  Normal   Created    42m (x3 over 123m)  kubelet  Created container loki
  Warning  Unhealthy  41m (x7 over 122m)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  41m (x6 over 122m)  kubelet  Liveness probe failed: HTTP probe failed with statuscode: 503
```

```
$ k logs loki-stack-0

level=error ts=2023-01-10T11:52:45.171326574Z caller=table.go:152 table-name=index_19367 msg="failed to remove working directory /data/loki/boltdb-shipper-compactor/index_19367" err="unlinkat /data/loki/boltdb-shipper-compactor/index_19367/.nfs00000000000a088e00003192: device or resource busy"
level=error ts=2023-01-10T11:52:45.171437058Z caller=compactor.go:492 msg="failed to compact files" table=index_19367 err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference"
level=error ts=2023-01-10T11:52:45.171593177Z caller=compactor.go:432 msg="failed to run compaction" err="recovered from panic opening boltdb file: runtime error: invalid memory address or nil pointer dereference"
```

**Comment by S0b1t** [comment]
@TsengSR 
Thanks for the answer !
After reading these topics, I'm starting to understand the situation.

> Resources on this topic:
> 
> * https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_are_nfsXXXX_files_and_how_do_I_delete_them
> * https://serverfault.com/questions/201294/nfsxxxx-files-appearing-what-are-those

By the way, I already set up the loki stack in another way, installed promtail using helm chart and set up loki on another ec2 instance on the host. 

I'm new in kubernetes, so after running a few microservices I started having other errors, like pod don't run, insufficient resources.

After reading this [Pod don't run, insufficient resources](https://stackoverflow.com/questions/53192999/pod-dont-run-insufficient-resources/53195147#53195147), I figured something out, on my NFS instance has 200 GB of storage of which 190 GB was given to other microservices. Then I created 30 GB pvc for loki stack. Hmm. Perhaps that's why "**_device or resource busy_**" in the log, but this is just a guess.

I have another k8s cluster, I will try the PLG stack with NFS again.

**Comment by TsengSR** [comment]
In our case its not the disk space,, Loki been acting like this since I tried to install it in the first place 3 month ago (We're at 60 GB out of 170 or so with 10 Gi for Loki). In the firs attempts we used loki configured with filesystem, later against s3 (using MinIO). It's persisting properly in MinIO, but the PVs used for write-ahead-log (wal) and cache are still on NFS and having the same issues with the .nfs000 files.

**Comment by darox** [comment]
I have moved to loki distributed and since then everything is working without any issue.

**Comment by TsengSR** [comment]
@darox 
> I have moved to loki distributed and since then everything is working without any issue.

Mind posting your values yaml and helm chart/version used? I've tried the bitnami helm charts, the distributed chart (based on 2.x helm charts) and the new 3.x unified helm chart. In all of them, the queriers/readers crash after some time

**Comment by jocelynthode** [comment]
I experience the same as @TsengSR. I feel like the real issue is that loki tries to read these `.nfs00...` files and obviously cannot process them.

**Comment by joyienjoy** [comment]
I am facing the same issue even today with Loki version 2.6.1, and any good work around is still not available.
After surfing through multiple git issue pages, it seems that It is an issue with Loki version 2.X. 
Can anyone confirm this. 
And, Please share if you have found a great solution to the issue

**Comment by S0b1t** [comment]
> it seems that It is an issue with Loki version 2.X. Can anyone confirm this.

I think so too

**Comment by saitama-24** [comment]
> > it seems that It is an issue with Loki version 2.X. Can anyone confirm this.
> 
> I think so too

Now do you have a better way to solve it？

**Comment by alexandreMegel** [comment]
In my case, I have deployed loki with Bitnami helm chart.

I just deleted the cache at this location: /bitnami/grafana-loki/loki/cache in the loki querier pods

And it works fine.

**Comment by TsengSR** [comment]
> In my case, I have deployed loki with Bitnami helm chart.
> 
> I just deleted the cache at this location: /bitnami/grafana-loki/loki/cache in the loki querier pods
> 
> And it works fine.

For a while maybe. The issue arises once the locally cached is filled and loki wants to store the files in the file storage (i.e. S3, NFS etc.) which it also succeeds storing, but it won't download them as it requires the index files which are not properly deleted/updated/synced between the pods when running on nfs and casuing a crash loop.

This usually happens after ~2 hours or after the a block/chunk is filled (iirc, ~2MB snappy compressed logs per chunk, means per unique combination of the labels you log into).

**Comment by sunidhi271** [comment]
I am trying to deploy simple scalable Loki chart version - version: "6.5.2", loki version 3.0.0, and promtail version 2.9.3/.
My read, write and backend components are crashing with whatever configurations I make. Below is the error logs in all the components: 
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/grafana/loki/v3/pkg/loki.validateSchemaRequirements(0xc000c54000)
        /src/loki/pkg/loki/validation.go:32 +0x72a
github.com/grafana/loki/v3/pkg/loki.(*Config).Validate(0xc000c54000)
        /src/loki/pkg/loki/loki.go:283 +0x12b2
main.main()
        /src/loki/cmd/loki/main.go:65 +0x5b3
```

I have even created a git issue - https://github.com/grafana/loki/issues/12972
It would be great if anyone can help in reviewing my configurations.

**Comment by JStickler** [comment]
Closing as stale. This issue was opened against a version of Loki that is no longer supported. If this issues still exists in more recent versions of Loki, please leave a comment and we can reopen the issue.
