### ISSUE TITLE
Label selectors in LogQL work in loki, but not in promtail match

### ISSUE THREAD

**Issue by davideshay** [grafana/loki#5209]
**Describe the bug**
I am trying to put a match selector in promtail to select by a range of http status codes. I am using this line here:

    - match: 
      selector: '{status=~".+",level !~ ".+"} | status>=100 status<=399'

This query standalone works fine in grafana/loki UI, but when using this as a selector in promtail config, I get this error:
`invalid match stage config: invalid selector syntax for match stage: parse error at line 1, col 28: syntax error: unexpected IDENTIFIER, expecting != or !~ or |~ or |="`

Was also documented on grafana forums by someone else: [https://community.grafana.com/t/promtail-2-3-0-label-filtering-no-longer-works-with-match-stage/52435](https://community.grafana.com/t/promtail-2-3-0-label-filtering-no-longer-works-with-match-stage/52435)

**To Reproduce**
1. Started Promtail daemonset - image grafana/loki:2.4.2
2. Ensure a match selector includes a label filter
3. Daemonset fails

**Expected behavior**
Queries that work in logQL in Grafana UI should work as logQL selectors, or if their are differences in operation they should be documented.

**Environment:**
 - Infrastructure: k3s, kubernetes daemonset
 - Deployment tool: yaml

**Comment by jeschkies** [comment]
I'm afraid LogQL is not supported in Promtail because of conflicting licenses. Promtail is Apache 2 and LogQL is AGPL 3.

You could encode the status in regular expressions `status=~"[1-3]\d{2}"`.

**Comment by davideshay** [comment]
That was roughly how I solved it. Documentation here is definitely unclear as it links to logql formats with no indication that only some subset of the functionality is available.

**Comment by jeschkies** [comment]
@davideshay would you say this is solved if the documentation was better?

**Comment by davideshay** [comment]
@jeschkies , Yes -- to me the key issue here was documentation. If I knew what the limits where and what was/wasn't supported, it's no problem working within those constraints.

**Comment by nekwar** [comment]
Is it possible to add what exact subset of LogQL functions is supported by Promtail's `match` function to the official documentation?

**Comment by martysohio** [comment]
I encountered this and its frustrating because the filter was ready to go then it errored as in the original post.  The documentation still appears to say you can use any LogQL there per https://grafana.com/docs/loki/latest/clients/promtail/stages/match/ unless this has changed in a year?

Grafana docs are very frustrating most of the time.

**Comment by ValentinVoigt** [comment]
Wow, this was frustrating. This needs to be documented correctly.

**Comment by ValentinVoigt** [comment]
From what I can see, this would indeed have helped a lot. Thank you very much!
