### ISSUE TITLE
Loki starting issue with legacy-read-mode parameter

### ISSUE THREAD

**Issue by gdubroeucq** [grafana/loki#8407]
**Describe the bug**
The _legacy-read-mode_ parameter affects the startup of some Loki components when starting in scaling mode (with helm)
When I run loki on Kubernetes, I encounter this error:

```
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
```

I can reproduce the issue in local if I add the _legacy-read-mode_ parameter as well.

This is annoying because the loki helm chart adds the legacy-read-mode parameter in multiple loki components.

Affected components:
> - loki-read
> - loki-backend

I am astonished that I am the first to see this issue, the bug look like added by the following commit since December 2022:
https://github.com/grafana/loki/commit/f5fbfabd8445b5f027d0da896bfa44c66829d705

**To Reproduce**
helm charts 4.4.2
loki 2.7.3

**Expected behavior**
Each loki components (reader, writer, backend, ...) run.

**Environment:**
 - Infrastructure: kubernetes and laptop
 - Deployment tool: helm (kubernetes), docker (laptop)

**Screenshots, Promtail config, or terminal output**

One component affected by the parameter:

```
---
# Source: loki/templates/read/deployment-read.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-read
  labels:
    app.kubernetes.io/part-of: memberlist
    helm.sh/chart: loki-4.4.2
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.7.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: read
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: read
  template:
    metadata:
      annotations:
        checksum/config: 5ecab9deb640e3c15ade0804cd26e3dc9be741c57663762c25991aab09b9344e
      labels:
        app.kubernetes.io/part-of: memberlist
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: read
    spec:
      serviceAccountName: loki
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: nexus-registry-proxies

      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      containers:
        - name: loki
          image: dockerhub.io/grafana/loki:2.7.3
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/config/config.yaml
            - -target=read
            - -legacy-read-mode=false
            - -common.compactor-grpc-address=loki-backend.loki.svc.cluster.local:9095
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: runtime-config
              mountPath: /etc/loki/runtime-config
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /var/loki
          resources:
            {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: loki
                  app.kubernetes.io/instance: release-name
                  app.kubernetes.io/component: read
              topologyKey: kubernetes.io/hostname

      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: loki
        - name: runtime-config
          configMap:
            name: loki-runtime
```

**Comment by DylanGuedes** [comment]
hey I didn't faced this when deploying a 4.5 helm chart from scratch earlier today. Do you mind trying it with the 4.5 version?

**Comment by DylanGuedes** [comment]
Ok, here's the fix:
```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
``` 
you need the `singleBinary` replicas to be higher than zero.
This is already fixed in the future docs [see here](https://grafana.com/docs/loki/next/installation/helm/install-monolithic/), you're seeing the docs that were released with Loki 2.7. Closing the issue, as the problem is already fixed in main.

**Comment by gdubroeucq** [comment]
> hey I didn't face this when deploying a 4.5 helm chart from scratch earlier today. Do you mind trying it with the 4.5 version?

Hello, I tried the 4.5 chart version but I got the same issue.

Then I was sure that the issue was with my Loki version, so in my chart value I deleted this:

```
loki:
  image:
    registry: nexus-registry.****
    repository: grafana/loki
    pullSecrets:
      - nexus-****
#    tag: 2.7.3        <-- I commented this part to see what version the chart will give me instead
```

And now the chart is working (yeah).
The Loki's helm chart version used is loki:main-5e53303 (why this version format??, look like weird instead of 2.7.x)

Can't we use simple digit version so it easier to know what loki version we use instead?

**Comment by DylanGuedes** [comment]
> And now the chart is working (yeah). 

Nice!

> The Loki's helm chart version used is loki:main-5e53303 (why this version format??, look like weird instead of 2.7.x)
> 
> Can't we use simple digit version so it easier to know what loki version we use instead?

Because you'll need changes that are already on main branch but not necessarily in the latest Loki version released. Releasing a new helm version is super easy and it allows us to deliver fixes to you much sooner; releasing a new Loki version on the other hand requires a lot of effort.

**Comment by weikinhuang** [comment]
I just encountered this in chart `4.6.0`, I see that the flags are still present in the chart templates here https://github.com/grafana/loki/blob/main/production/helm/loki/templates/backend/statefulset-backend.yaml#L77 and here https://github.com/grafana/loki/blob/main/production/helm/loki/templates/read/deployment-read.yaml#L63

**Comment by gdubroeucq** [comment]
> I just encountered this in chart `4.6.0`, I see that the flags are still present in the chart templates here https://github.com/grafana/loki/blob/main/production/helm/loki/templates/backend/statefulset-backend.yaml#L77 and here https://github.com/grafana/loki/blob/main/production/helm/loki/templates/read/deployment-read.yaml#L63.
> 
> I'm also not defining the image version, which automatically pulled `2.7.3`
> 
> Edit: nevermind, I see that in the changelog, 3 target was reverted. I ran into this issue because `renovatebot` updated my chart version automatically.

`4.6.0` definitly fixed the issue because Loki version is `2.7.3` by default now in the chart.

**Comment by SzekeresB** [comment]
The issue is still present in `4.6.1` with  Loki version is 2.7.3. (Fresh install)
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "grafana" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm upgrade --install loki-ng grafana/loki --namespace loki-ng --create-namespace -f loki_values.yaml
Release "loki-ng" does not exist. Installing it now.
NAME: loki-ng
LAST DEPLOYED: Tue Feb 14 12:59:58 2023
NAMESPACE: loki-ng
STATUS: deployed
REVISION: 1
NOTES:
***********************************************************************
 Welcome to Grafana Loki
 Chart version: 4.6.1
 Loki version: 2.7.3
***********************************************************************

Installed components:
* grafana-agent-operator
* gateway
* read
* write
* backend
```
The Helm list output.
```
$ helm list -A
NAME                            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
loki-ng                         loki-ng                 1               2023-02-14 12:59:58.889306404 +0000 UTC deployed        loki-4.6.1      2.7.3      
```
`loki-reader` crashing and `loki-backend` crashing:
```
$ kubectl get pods -n loki-ng 
NAME                                              READY   STATUS             RESTARTS      AGE
loki-backend-0                                    0/1     Error              5 (83s ago)   2m52s
loki-backend-1                                    0/1     CrashLoopBackOff   4 (83s ago)   2m52s
loki-backend-2                                    0/1     CrashLoopBackOff   4 (73s ago)   2m52s
loki-canary-64tpn                                 1/1     Running            0             2m52s
loki-canary-cfgw9                                 1/1     Running            0             2m52s
loki-canary-fqjtd                                 1/1     Running            0             2m52s
loki-canary-zpwh7                                 1/1     Running            0             2m52s
loki-gateway-cff69cfb5-rs2qw                      1/1     Running            0             2m52s
loki-ng-grafana-agent-operator-797d5bbcc8-jzdq5   1/1     Running            0             2m52s
loki-ng-logs-4wtcl                                2/2     Running            0             2m42s
loki-ng-logs-87dg2                                2/2     Running            0             2m42s
loki-ng-logs-hkfkz                                2/2     Running            0             2m42s
loki-ng-logs-sm9rg                                2/2     Running            0             2m42s
loki-read-5d8bdcc666-5kz9t                        0/1     CrashLoopBackOff   4 (73s ago)   2m52s
loki-read-5d8bdcc666-7xzrg                        0/1     CrashLoopBackOff   4 (66s ago)   2m52s
loki-read-5d8bdcc666-k9cwf                        0/1     CrashLoopBackOff   4 (61s ago)   2m52s
loki-write-0                                      1/1     Running            0             2m52s
loki-write-1                                      1/1     Running            0             2m52s
loki-write-2                                      1/1     Running            0             2m52s
```
The Loki read deployment:
```
$ kubectl get deployments.apps -n loki-ng loki-read -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: loki-ng
    meta.helm.sh/release-namespace: loki-ng
  creationTimestamp: "2023-02-14T13:00:07Z"
  generation: 1
  labels:
    app.kubernetes.io/component: read
    app.kubernetes.io/instance: loki-ng
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.7.3
    helm.sh/chart: loki-4.6.1
  name: loki-read
  namespace: loki-ng
  resourceVersion: "180766778"
  uid: 8aa7dba6-4d20-4452-a7dd-e949c1c3d580
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: read
      app.kubernetes.io/instance: loki-ng
      app.kubernetes.io/name: loki
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 4923a01bf8b18783910b2e6ba1063d291338dd5857490eba01b285e5f1f03d8f
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: read
        app.kubernetes.io/instance: loki-ng
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: memberlist
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: read
                app.kubernetes.io/instance: loki-ng
                app.kubernetes.io/name: loki
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
      - args:
        - -config.file=/etc/loki/config/config.yaml
        - -target=read
        - -legacy-read-mode=false
        - -common.compactor-grpc-address=loki-backend.loki-ng.svc.cluster.local:9095
        image: docker.io/grafana/loki:2.7.3
        imagePullPolicy: IfNotPresent
        name: loki
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        - containerPort: 7946
          name: http-memberlist
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/loki/config
          name: config
        - mountPath: /etc/loki/runtime-config
          name: runtime-config
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/loki
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: false
        runAsUser: 10001
      serviceAccount: loki
      serviceAccountName: loki
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          name: loki
        name: config
      - configMap:
          defaultMode: 420
          name: loki-runtime
        name: runtime-config
```
Read logs:
```
$ kubectl logs -n loki-ng loki-read-5d8bdcc666-5kz9t
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
$ kubectl logs -n loki-ng loki-read-5d8bdcc666-7xzrg
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
$ kubectl logs -n loki-ng loki-read-5d8bdcc666-k9cwf
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
```
Backend logs:
```
$ kubectl logs -n loki-ng loki-backend-0
Defaulted container "loki" out of: loki, init-backend (init)
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
$ kubectl logs -n loki-ng loki-backend-1
Defaulted container "loki" out of: loki, init-backend (init)
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
$ kubectl logs -n loki-ng loki-backend-2
Defaulted container "loki" out of: loki, init-backend (init)
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
```

Note: Changing in the values does help:
```
loki:
  image:
    tag: main-5e53303
```
From the default:
```
loki:
  image:
    tag: null
```
